

orbs:
  python: circleci/python@0.3.2
python:
  version: 3.5.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      #- python/install-dep
      #- python/save-cache
      - run:
          name: numba
          command: pip install git+https://github.com/russelljjarvis/jit_hub.git;
      - run:
          name: conda
          command: sudo conda install scipy;

      - run:
          name: install
          command: sudo pip install pip --upgrade; sudo pip install -r requirements.txt;

      #- run:
      #    name: more
      #    command: sudo python setup.py install;

workflows:
  main:
    jobs:
      - build-and-test
